# Generated by Django 3.0.8 on 2020-07-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default=18, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profession',
            field=models.CharField(default='student', max_length=100),
            preserve_default=False,
        ),
    ]
