# Generated by Django 3.0.8 on 2020-07-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20200711_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('indian_news', models.TextField()),
                ('national_news', models.TextField()),
                ('international_news', models.TextField()),
                ('bollywood_news', models.TextField()),
                ('lifestyle_news', models.TextField()),
                ('sport_news', models.TextField()),
                ('business_news', models.TextField()),
                ('sharemarket_news', models.TextField()),
                ('corona_news', models.TextField()),
                ('space_news', models.TextField()),
                ('motivation_news', models.TextField()),
            ],
        ),
    ]
