# Generated by Django 3.0.8 on 2020-07-11 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city_news',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='state_news',
            field=models.TextField(blank=True),
        ),
    ]
