# Generated by Django 3.0.8 on 2020-07-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_userinfo_key_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bestpick_news',
            field=models.TextField(blank=True),
        ),
    ]
