# Generated by Django 3.0.8 on 2020-07-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_userinfo_bestpick_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
