# Generated by Django 3.0.8 on 2020-07-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20200717_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sourcenews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hindu', models.TextField()),
                ('gnews', models.TextField()),
                ('toi', models.TextField()),
                ('bloom', models.TextField()),
                ('buss', models.TextField()),
                ('fortune', models.TextField()),
                ('bbc', models.TextField()),
                ('espn', models.TextField()),
                ('foxsport', models.TextField()),
                ('natgeo', models.TextField()),
                ('nextbig', models.TextField()),
                ('tech', models.TextField()),
                ('newsci', models.TextField()),
                ('mtv', models.TextField()),
                ('buzz', models.TextField()),
                ('mnt', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
    ]
